# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
In order to answer this question, we must define what makes a function safe or not. Based on my understanding, a safe function is one that handles any potential errors in order to avoid crashing or unexpected behavior. With that definition in mind, I don't believe the code snippet above is a safe function. While the function may run, it lacks the functionality to throw errors and "catch" errors which is normally done with `try/catch`. It is important to explicitly handle these errors, so when they occur, we are given an indication of what went wrong. In this function, I can imagine an where things could go wrong, such as providing an invalid input.

# Teacher Feedback